media: blog-images

content:
  - name: blog
    label: Blog Posts
    path: src/content/blog
    type: collection
    fields:
      - name: title
        label: Title
        type: text
        required: true
        description: "Keep it concise and compelling"
      - name: description
        label: Description
        type: textarea
        required: true
        description: "Brief summary for SEO and previews"
      - name: publishDate
        label: Publish Date
        type: date
        required: true
        default: today
      - name: draft
        label: Draft
        type: boolean
        default: false
        description: "Uncheck to publish"
      - name: image
        label: Featured Image
        type: image
        description: "Optional cover image"
      - name: body
        label: Content
        type: rich-text
        required: true
        options:
          path: blog-images
          extensions: [jpg, jpeg, png, webp, gif]

  - name: projects
    label: Projects
    path: src/content/projects
    type: collection
    fields:
      - name: title
        label: Title
        type: text
        required: true
      - name: description
        label: Description
        type: textarea
        required: true
        description: "Brief project summary"
      - name: status
        label: Status
        type: select
        options:
          values:
            - active
            - completed
            - paused
            - archived
        default: active
      - name: link
        label: Project Link
        type: string
        description: "GitHub, demo, or project URL"
        pattern: "^https?://.+"
      - name: order
        label: Display Order
        type: number
        default: 1
        description: "Lower numbers appear first"
      - name: body
        label: Detailed Description
        type: rich-text
        options:
          path: project-images
          extensions: [jpg, jpeg, png, webp]

  - name: updates
    label: Quick Updates
    path: src/content/updates
    type: collection
    fields:
      - name: title
        label: Title
        type: text
        required: true
        description: "Short, descriptive title"
      - name: publishDate
        label: Publish Date
        type: date
        required: true
        default: today
      - name: link
        label: External Link
        type: string
        description: "Link to article, video, or resource (optional)"
        required: false
      - name: linkTitle
        label: Link Title
        type: text
        description: "Display name for the external link"
      - name: body
        label: Your Thoughts
        type: rich-text
        required: true
        description: "Your commentary, thoughts, or quick notes"
        options:
          path: update-images
          extensions: [jpg, jpeg, png, webp]