media: public/blog-images

content:
  - name: blog
    label: Blog Posts
    path: src/content/blog
    type: collection
    fields:
      - name: title
        label: Title
        type: text
        required: true
        width: half
        description: "Keep it concise and compelling"
      - name: description
        label: Description
        type: textarea
        required: true
        description: "Brief summary for SEO and previews"
      - name: publishDate
        label: Publish Date
        type: date
        required: true
        default: today
      - name: draft
        label: Draft
        type: boolean
        default: false
        description: "Uncheck to publish"
      - name: image
        label: Featured Image
        type: image
        description: "Optional cover image"
      - name: body
        label: Content
        type: richtext
        required: true

  - name: projects
    label: Projects
    path: src/content/projects
    type: collection
    fields:
      - name: title
        label: Title
        type: text
        required: true
        width: half
      - name: description
        label: Description
        type: textarea
        required: true
        description: "Brief project summary"
      - name: status
        label: Status
        type: select
        options:
          - active
          - completed
          - paused
          - archived
        default: active
      - name: link
        label: Project Link
        type: url
        description: "GitHub, demo, or project URL"
      - name: order
        label: Display Order
        type: number
        default: 1
        description: "Lower numbers appear first"
      - name: body
        label: Detailed Description
        type: richtext

  - name: updates
    label: Quick Updates
    path: src/content/updates
    type: collection
    fields:
      - name: title
        label: Title
        type: text
        required: true
        width: half
        description: "Short, descriptive title"
      - name: publishDate
        label: Publish Date
        type: date
        required: true
        default: today
      - name: link
        label: External Link
        type: url
        description: "Link to article, video, or resource (optional)"
      - name: linkTitle
        label: Link Title
        type: text
        description: "Display name for the external link"
      - name: body
        label: Your Thoughts
        type: richtext
        required: true
        description: "Your commentary, thoughts, or quick notes"