base_url = "https://bebhuvan.pages.dev"
title = "Bhuvan"
description = "I do a lot of random shit and this is a log of all that I do."
theme = "tabi"
generate_feeds = true
compile_sass = true
build_search_index = true
default_language = "en"

taxonomies = [
    {name = "tags", feed = true}
]

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"
smart_punctuation = true

[extra]
theme_switcher = true
skin = "teal"
browser_theme_color = "#087e96"
show_author = true
show_reading_time = true
show_date = true

menu = [
    { name = "blog", url = "blog", trailing_slash = true },
    { name = "archive", url = "archive", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true }
]

feed_icon = true
